on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
  release:
    types:
      - created

jobs:
  test_windows_gmt8:
    runs-on: windows-latest
    name: Test GMT +8 on Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set Timezone to +8 (With input)
        uses: ./
        with:
          timezoneWindows: "Hong Kong Standard Time"
      - run: npm i
      - run: npm run test
