on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
  release:
    types:
      - created

jobs:
  test_action:
    name: Test Run Action
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set Timezone to +0 (No input)
        uses: ./
      - name: Set Timezone to +0 (With input)
        uses: ./
        with:
          timezoneLinux: "UTC"
          timezoneMacos: "GMT"
          timezoneWindows: "UTC"
      - name: Set Timezone to +8 (With input)
        uses: ./
        with:
          timezoneLinux: "Asia/Hong_Kong"
          timezoneMacos: "Asia/Hong_Kong"
          timezoneWindows: "Hong Kong Standard Time"
